name: Python Test

on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest, macos-latest]
        copy_cmd: [cp]
        include:
          - os: windows-latest
            copy_cmd: copy
            python-version: 3.9
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip flake8 pytest
        pip install -r requirements.txt
    - name: Setup test configuration
      run: |
        ${{ matrix.copy_cmd }} bdfr/default_config.cfg ./test_config.cfg
        echo >> ./test_config.cfg
        echo user_token = ${{ secrets.REDDIT_TEST_TOKEN }} >> ./test_config.cfg
    - name: Lint w/ flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Test w/ PyTest
      run: |
        pytest -m 'not slow' --verbose
